//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by chcsva.rc
//
#define IDI_MAIN_ICON                   5
#define IDC_CONFIGURE                   7
#define IDR_CHCS                        101
#define IDD_ARCHIVE_WRITE               103
#define IDD_CONFIGURE                   103
#define IDD_COMPRESSOR                  104
#define IDR_SYSTRAY_MENU                106
#define IDI_ICON1                       107
#define IDS_STRING108                   108
#define IDS_DEFAULT_BASEPATH            108
#define IDS_CHCS_DEFAULT_ARCHIVE_BASEPATH 108
#define IDS_CHCS_REGISTRY_KEY           109
#define IDD_DIALOG1                     110
#define IDD_SHOWSTREAM                  110
#define IDD_DIALOG2                     111
#define IDD_VIDEOPROC_AMP               111
#define IDD_MANAGER                     112
#define IDI_ICON2                       114
#define IDI_MAIN_ICON_CLIENT            114
#define IDI_ICON3                       115
#define IDI_NOSIGNAL                    115
#define IDC_DECODER_TIME                1001
#define IDC_DECODER_FRAME               1002
#define IDC_DECODER_FORMAT              1003
#define IDC_DRIVER_NAME                 1004
#define IDC_DRIVER_PATH                 1005
#define IDC_DRIVER_DESC                 1006
#define IDC_SELECT_DRIVER               1007
#define IDC_SELECT_CODEC                1007
#define IDC_EDIT2                       1008
#define IDC_VIDEO_FPM                   1008
#define IDC_EDIT3                       1009
#define IDC_STATIC_DATARATE             1009
#define IDC_VIDEO_MAXRATE               1009
#define IDC_STATIC_KEYRATE              1010
#define IDC_BROWSE_DATABASE             1010
#define IDC_STATIC_INFO                 1011
#define IDC_BROWSE_BASEPASE             1011
#define IDC_BROWSE_BASEPATH             1011
#define IDC_DATABASE                    1012
#define IDC_BASEPATH                    1013
#define IDC_CHECK1                      1014
#define IDC_BRIGHTNESS_AUTO             1014
#define IDC_VIDEO_FPM2                  1014
#define IDC_SLIDER1                     1015
#define IDC_BRIGHTNESS_SLIDER           1015
#define IDC_EDIT1                       1016
#define IDC_BRIGHTNESS_EDIT             1016
#define IDC_BASEPATH2                   1016
#define IDC_CHECK2                      1017
#define IDC_CONTRAST_AUTO               1017
#define IDC_BROWSE_BASEPATH2            1017
#define IDC_SLIDER2                     1018
#define IDC_CONTRAST_SLIDER             1018
#define IDC_SELECT_CODEC2               1018
#define IDC_EDIT4                       1019
#define IDC_CONTRAST_EDIT               1019
#define IDC_CHECK3                      1020
#define IDC_HUE_AUTO                    1020
#define IDC_SLIDER3                     1021
#define IDC_HUE_SLIDER                  1021
#define IDC_EDIT5                       1022
#define IDC_HUE_EDIT                    1022
#define IDC_CHECK4                      1023
#define IDC_SATURATION_AUTO             1023
#define IDC_SLIDER4                     1024
#define IDC_SATURATION_SLIDER           1024
#define IDC_EDIT6                       1025
#define IDC_SATURATION_EDIT             1025
#define IDC_CHECK5                      1026
#define IDC_SHARPNESS_AUTO              1026
#define IDC_SLIDER5                     1027
#define IDC_SHARPNESS_SLIDER            1027
#define IDC_EDIT7                       1028
#define IDC_SHARPNESS_EDIT              1028
#define IDC_CHECK6                      1029
#define IDC_GAMMA_AUTO                  1029
#define IDC_SLIDER6                     1030
#define IDC_GAMMA_SLIDER                1030
#define IDC_EDIT8                       1031
#define IDC_GAMMA_EDIT                  1031
#define IDC_CHECK7                      1032
#define IDC_WHITEBLNC_AUTO              1032
#define IDC_SLIDER7                     1033
#define IDC_WHITEBLNC_SLIDER            1033
#define IDC_EDIT9                       1034
#define IDC_WHITEBLNC_EDIT              1034
#define IDC_CHECK8                      1035
#define IDC_SLIDER8                     1036
#define IDC_BACKLIGHT_SLIDER            1036
#define IDC_EDIT10                      1037
#define IDC_BACKLIGHT_EDIT              1037
#define IDC_BRIGHTNESS_SPIN             1038
#define IDC_CONTRAST_SPIN               1039
#define IDC_HUE_SPIN                    1040
#define IDC_SATURATION_SPIN             1041
#define IDC_SHARPNESS_SPIN              1042
#define IDC_GAMMA_SPIN                  1043
#define IDC_WHITEBLNC_SPIN              1044
#define IDC_BACKLIGHT_SPIN              1045
#define IDC_BRIGHTNESS_STATIC           1046
#define IDC_CONTRAST_STATIC             1047
#define IDC_HUE_STATIC                  1048
#define IDC_SATURATION_STATIC           1049
#define IDC_SHARPNESS_STATIC            1050
#define IDC_GAMMA_STATIC                1051
#define IDC_WHITEBLNC_STATIC            1052
#define IDC_BACKLIGHT_STATIC            1053
#define IDC_CHECK9                      1054
#define IDC_COLOR_ENABLE                1054
#define IDC_STREAMS_LIST                1055
#define IDC_SPIN1                       1056
#define IDC_SPIN2                       1057
#define IDC_SPIN3                       1058
#define IDC_DATARATE                    1152
#define IDC_KEYRATE                     1153
#define IDC_USE_DATARATE                1184
#define IDC_COMP_LIST                   1267
#define IDC_USE_KEYFRAMES               1268
#define IDC_STATIC_DELTA                1273
#define IDC_STATIC_FOURCC               1274
#define IDC_STATIC_DRIVER               1275
#define IDC_QUALITY_SLIDER              1280
#define IDC_EDIT_QUALITY                1289
#define ID_TRAY_EXIT                    40002
#define ID_TRAY_SHOW                    40005
#define ID_TRAY_UPDATE                  40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
